### ISSUE TITLE
RFC: upstreaming this implementation to scipy

### ISSUE THREAD

**Issue by dschmitz89** [antoinecollet5/lbfgsb#1]
SciPy is trying to remove all Fortran code: see https://github.com/scipy/scipy/issues/18566

This repo looks like a young, but very nicely maintained and thoroughly tested implementation of the L-BFGS-B algorithm and is far more understandable than the F77 goto mess we currently have, so my question is: would you be open to contribute your code to SciPy?

If yes, we would need to know if you have detailed benchmarks against Scipy's implementation.

CC @ilayn

**Comment by antoinecollet5** [comment]
Hi @dschmitz89, 

First issue and what an issue! Contributing to scipy would be a real honor! Thank you for your interest.

Indeed, the repo is young and as you can see in the history, I'm still correcting a lot of things at the moment. The original code is pretty damn good, and it's not easy to reproduce the behavior in fine detail. To be perfectly honest, I've relied heavily on the work of Jacob Williams [(lbfgsb in F90)](https://github.com/jacobwilliams/lbfgsb), who had the wisdom to get rid of those famous F77 gotos. F90 is much easier to digest.

By the way, he did the same for [slsqp](https://github.com/jacobwilliams/slsqp), which must also be on your list (https://github.com/scipy/scipy/blob/main/scipy/optimize/slsqp/slsqp_optmz.f)? Maybe I'll port it to Python in a few months, as I'll be using this solver in my work.

Coming back to this LBFGSB implementation, I think you know it well, but it's more memory- and computation-intensive than Fortran code. But in my opinion, this will always be negligible compared with the calculation of the objective function and its gradient (at least in most problems).

Before possibly porting this code to scipy, however, I'd like to complete a few things here
- Get the tests up to 100%. In fact, a lot of unit tests are missing -> I've got a small (long) list of things to test...
- Refine the documentation, and in particular review the equations and replace all the __description__ that hang around here and there.
- Clean up comments and check references
- Implement various linesearch algo's and test them -> most of them are already in scipy, great!
- Explain and document the logging usage 
- Document stop criteria and how to use them
- ... some other cool stuff

It should not take too long.

As far as benchmarking with the current scipy code is concerned, that's a work in progress. I've already implemented a number of [functions for this](https://github.com/antoinecollet5/lbfgsb/blob/master/lbfgsb/benchmarks.py) and done a lot of 2D testing on problems with several thousand parameters as part of my work ([see pyrtid which is also under construction](https://github.com/antoinecollet5/pyrtid)).

Cheers
Antoine

**Comment by ilayn** [comment]
This is wonderful work. Congratulations. If it is any better, I already ported this to C and indeed I have been going through a lot of versions in C. However many are in GPL license hence I did not have a chance to get any insights. 

But, since I am slightly going mental from all these F77 code, this testing scheme that you have is golden ticket for us. Because the correctness is the only way to debug fortran code and if you are willing to collaborate, I can do the extremely boring part of the translation (which I already did almost completely) and we can use your testing suite to beat the shit out of the code. 

In fact, if you think your translation is better and uses modern things like matrix multiplications (I myself can't believe I am calling matmul modern, I know) and NumPy stuff I can easily convert it to C and we can directly benefit from the low-level stuff.

**Comment by ilayn** [comment]
One of the major problems with C code you see online is that they are the cleanedup `f2c` translations which is not portable enough to be used and carries over all the memory bugs and segfault behavior. That's why I went through hell to translate all our F77 code. Typically to unroll gotos is quite alright if the authors are not nasty coders. But some code is just insanity hence I leave a bit of those if it becomes a mess of code repetition.
